class Location {
  // This class is not meant to be instantiated or extended; this constructor
  // prevents instantiation and extension.
  Location._();

  static const List<String> counties = <String>[
    'Bedfordshire',
    'Berkshire',
    'Bristol',
    'Buckinghamshire',
    'Cambridgeshire',
    'Cheshire',
    'Cornwall',
    'Cumbria',
    'Derbyshire',
    'Devon',
    'Dorset',
    'Durham',
    'East Riding of Yorkshire',
    'East Sussex',
    'Essex',
    'Gloucestershire',
    'Greater Manchester',
    'Hampshire',
    'Hereford and Worcester',
    'Hertfordshire',
    'Isle of Man',
    'Isle of Wight',
    'Kent',
    'Lancashire',
    'Leicestershire',
    'Lincolnshire',
    'London',
    'Merseyside',
    'Middlesex',
    'Norfolk',
    'North Yorkshire',
    'Northamptonshire',
    'Northumberland',
    'Nottinghamshire',
    'Oxfordshire',
    'Rutland',
    'Shropshire',
    'Somerset',
    'South Yorkshire',
    'Staffordshire',
    'Suffolk',
    'Surrey',
    'Tyne and Wear',
    'Warwickshire',
    'West Midlands',
    'West Sussex',
    'West Yorkshire',
    'Wiltshire',
    'County Antrim',
    'County Armagh',
    'County Down',
    'County Fermanagh',
    'County Londonderry',
    'County Tyrone',
    'Aberdeen',
    'Aberdeenshire',
    'Angus',
    'Argyll and Bute',
    'Clackmannanshire',
    'Dumfries and Galloway',
    'Dundee',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Lothian',
    'East Renfrewshire',
    'Edinburgh',
    'Falkirk',
    'Fife',
    'Glasgow',
    'Highland',
    'Inverclyde',
    'Midlothian',
    'Moray',
    'North Ayrshire',
    'North Lanarkshire',
    'Orkney',
    'Perth and Kinross',
    'Renfrewshire',
    'Scottish Borders',
    'Shetland Isles',
    'South Ayrshire',
    'South Lanarkshire',
    'Stirlingshire',
    'West Dunbartonshire',
    'West Lothian',
    'Western Isles',
    'Anglesey/Sir Fon',
    'Blaenau Gwent',
    'Bridgend',
    'Caerphilly',
    'Cardiff',
    'Carmarthenshire',
    'Ceredigion',
    'Conwy',
    'Denbighshire',
    'Flintshire',
    'Glamorgan',
    'Gwynedd',
    'Merthyr Tydfil',
    'Monmouthshire',
    'Neath Port Talbot',
    'Newport',
    'Newport City',
    'Pembrokeshire',
    'Powys',
    'Rhondda Cynon Taff',
    'Swansea',
    'Torfaen',
    'Wrexham',
  ];
}
